version: '3.9'

services:
  mongodb:
    image: mongo:7.0
    container_name: chat-app-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - chat-network

  redis:
    image: redis:7.2-alpine
    container_name: chat-app-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - chat-network

volumes:
  mongo_data:
  redis_data:

networks:
  chat-network:
    driver: bridge